const std = @import("std");
const Writer = std.Io.Writer;
const oom = @import("misc").oom;

pub const AnalyzerMsg = union(enum) {
    already_declared: struct { name: []const u8 },
    already_declared_param: struct { name: []const u8 },
    already_declared_field: struct { name: []const u8 },
    array_mismatch_dim: struct { declared: usize, accessed: usize },
    assign_to_constant: struct { name: []const u8 },
    assign_to_struct_fn,
    assign_type,
    big_self_outside_struct,
    block_all_path_dont_return,
    break_val_in_non_val_block,
    call_method_on_type: struct { name: []const u8 },
    call_static_on_instance: struct { name: []const u8 },
    cant_infer_array_type,
    cond_alias_non_optional: struct { found: []const u8 },
    dead_code,
    default_value_type_mismatch: struct {
        expect: []const u8,
        found: []const u8,
        kind: []const u8,

        pub fn new(expect: []const u8, found: []const u8, kind: enum { field, param }) @This() {
            return .{ .expect = expect, .found = found, .kind = @tagName(kind) };
        }
    },
    dot_type_on_non_mod: struct { found: []const u8 },
    duplicate_field: struct { name: []const u8 },
    duplicate_param: struct { name: []const u8 },
    enum_dup_tag: struct { name: []const u8 },
    enum_tag_access,
    enum_unknown_field: struct { @"enum": []const u8, field: []const u8 },
    float_equal,
    fn_expect_value: struct { expect: []const u8 },
    invalid_arithmetic: struct { found: []const u8 },
    invalid_assign_target,
    invalid_call_target,
    invalid_comparison: struct { found1: []const u8, found2: []const u8 },
    invalid_logical: struct { found: []const u8 },
    invalid_unary: struct { found: []const u8 },
    missing_symbol_in_module: struct { symbol: []const u8, module: []const u8 },
    missing_else_clause: struct { if_type: []const u8 },
    missing_field_struct_literal: struct { name: []const u8 },
    missing_file_in_module: struct { file: []const u8 },
    missing_function_param: struct { name: []const u8 },
    named_arg_in_bounded,
    no_main,
    non_array_indexing: struct { found: []const u8 },
    non_bool_cond: struct { what: []const u8, found: []const u8 },
    non_integer_index: struct { found: []const u8 },
    non_null_comp_optional: struct { found: []const u8 },
    non_struct_field_access: struct { found: []const u8 },
    non_struct_struct_literal,
    null_assign_to_non_optional: struct { expect: []const u8 },
    return_outside_fn,
    self_outside_struct,
    too_many_fn_args: struct { expect: usize, found: usize },
    too_many_locals,
    too_many_types,
    type_mismatch: struct { expect: []const u8, found: []const u8 },
    type_not_in_union: struct { expect: []const u8, found: []const u8 },
    undeclared_field_access: struct { name: []const u8 },
    undeclared_block_label: struct { name: []const u8 },
    undeclared_type: struct { found: []const u8 },
    undeclared_var: struct { name: []const u8 },
    unknow_char_escape: struct { found: []const u8 },
    unknown_module: struct { name: []const u8 },
    unknown_param: struct { name: []const u8 },
    unknown_struct_field: struct { name: []const u8 },
    non_comptime_in_global,
    non_comptime_default: struct {
        kind: []const u8,

        pub fn new(kind: enum { field, parameter }) @This() {
            return .{ .kind = @tagName(kind) };
        }
    },
    use_uninit_var: struct { name: []const u8 },
    void_array,
    void_param,
    void_value,
    when_arm_duplicate,
    when_arm_not_in_union: struct { found: []const u8, expect: []const u8 },
    when_non_exhaustive: struct { missing: []const u8 },
    when_with_non_union: struct { found: []const u8 },

    const Self = @This();

    pub fn getMsg(self: Self, writer: *Writer) !void {
        try switch (self) {
            .already_declared => |e| writer.print("identifier '{s}' is already declared in this scope", .{e.name}),
            .already_declared_field => |e| writer.print("a field named '{s}' already exist in structure declaration", .{e.name}),
            .already_declared_param => |e| writer.print("identifier '{s}' is already used in parameters list", .{e.name}),
            .array_mismatch_dim => |e| writer.print("trying to access dimension {} of a {}-dimensions array", .{ e.accessed, e.declared }),
            .assign_to_constant => |e| writer.print("can't assign to constant variable '{s}'", .{e.name}),
            .assign_to_struct_fn => writer.writeAll("can't assign to structure's functions"),
            .assign_type => writer.writeAll("trying to assign a type"),
            .big_self_outside_struct => writer.writeAll("can't use 'Self' outside a structure"),
            .block_all_path_dont_return => writer.writeAll("all paths of block expression don't return a value"),
            .break_val_in_non_val_block => writer.writeAll("can't return a value from this scope"),
            .call_method_on_type => |e| writer.print("method '{s}' called on a type", .{e.name}),
            .call_static_on_instance => |e| writer.print("static function '{s}' called on an instance", .{e.name}),
            .cant_infer_array_type => writer.writeAll("can't infer array type with empty array and not declared type"),
            .cond_alias_non_optional => |e| writer.print(
                "can't alias non-optional types in 'if' and 'while' conditions, found '{s}'",
                .{e.found},
            ),
            .dead_code => writer.writeAll("unreachable code"),
            .default_value_type_mismatch => |e| writer.print(
                "{s}'s default value doesn't match {s}'s type, expect '{s}' but found '{s}'",
                .{ e.kind, e.kind, e.expect, e.found },
            ),
            .dot_type_on_non_mod => |e| writer.print("can't use a non-module member as a type, found '{s}'", .{e.found}),
            .duplicate_field => |e| writer.print("field '{s}' is already present in structure literal", .{e.name}),
            .duplicate_param => |e| writer.print("parameter '{s}' is already present in function call", .{e.name}),
            .enum_dup_tag => |e| writer.print("tag '{s}' already declared in enum", .{e.name}),
            .enum_tag_access => writer.writeAll("can't access enum's tag at runtime"),
            .enum_unknown_field => |e| writer.print("enum '{s}' have no tag and no declaration '{s}'", .{ e.@"enum", e.field }),
            .float_equal => writer.writeAll("floating-point values equality is unsafe"),
            .fn_expect_value => |e| writer.print("no value returned from function expecting '{s}'", .{e.expect}),
            .invalid_arithmetic => |e| writer.print("invalid arithmetic operation on type '{s}'", .{e.found}),
            .invalid_assign_target => writer.writeAll("invalid assignment target"),
            .invalid_call_target => writer.writeAll("invalid call target, can only call functions and methods"),
            .invalid_comparison => |e| writer.print("invalid comparison between types '{s}' and '{s}'", .{ e.found1, e.found2 }),
            .invalid_logical => writer.writeAll("logical operators must be used with booleans"),
            .invalid_unary => writer.writeAll("invalid unary operation"),
            .missing_symbol_in_module => |e| writer.print("no symbol named '{s}' in module '{s}'", .{ e.symbol, e.module }),
            .missing_else_clause => writer.writeAll("'if' is missing an 'else' clause"),
            .missing_field_struct_literal => |e| writer.print("missing field '{s}' in structure literal", .{e.name}),
            .missing_file_in_module => |e| writer.print("module doesn't contain file '{s}'", .{e.file}),
            .missing_function_param => |e| writer.print("missing argument '{s}'", .{e.name}),
            .named_arg_in_bounded => writer.writeAll("named argument are not allowed with bounded functions"),
            .no_main => writer.writeAll("no main function found"),
            // TODO: when there will be traits and index trait, change description
            .non_array_indexing => |e| writer.print("can only index arrays, found '{s}'", .{e.found}),
            .non_bool_cond => |e| writer.print("non boolean condition, found type '{s}'", .{e.found}),
            .non_integer_index => |e| writer.print("non integer index, found '{s}'", .{e.found}),
            .non_null_comp_optional => |e| writer.print("can't compare anything else than 'null' to optional type, found '{s}'", .{e.found}),
            .non_struct_field_access => writer.writeAll("attempting to access a field on a non structure type"),
            .non_struct_struct_literal => writer.writeAll("structure literal syntax is for structure type "),
            .null_assign_to_non_optional => |e| writer.print("can't assign 'null' to non-optional type '{s}'", .{e.expect}),
            .return_outside_fn => writer.writeAll("return outside of a function"),
            .self_outside_struct => writer.writeAll("only structure's methods can refer to 'self'"),
            .too_many_locals => writer.writeAll("too many local variables, maximum is 255"),
            .too_many_fn_args => |e| writer.print("expect maximum {} arguments but found {}", .{ e.expect, e.found }),
            .too_many_types => writer.writeAll("too many types declared, maximum is 268435455"),
            .type_mismatch => |e| writer.print("type mismatch, expect type '{s}' but found '{s}' ", .{ e.expect, e.found }),
            .type_not_in_union => |e| writer.print("type `{s}' is not part of union '{s}'", .{ e.found, e.expect }),
            .undeclared_field_access => |e| writer.print("field '{s}' isn't part of structure's definition", .{e.name}),
            .undeclared_block_label => |e| writer.print("no block labelled '{s}' found in scope", .{e.name}),
            .undeclared_type => |e| writer.print("undeclared type '{s}'", .{e.found}),
            .undeclared_var => |e| writer.print("undeclared variable '{s}'", .{e.name}),
            .unknow_char_escape => |e| writer.print("unknow character escape '{s}'", .{e.found}),
            .unknown_module => |e| writer.print("unknown module '{s}'", .{e.name}),
            .unknown_param => |e| writer.print("function doesn't have parameter '{s}'", .{e.name}),
            .unknown_struct_field => |e| writer.print("unknown structure's field '{s}'", .{e.name}),
            .non_comptime_in_global => writer.writeAll("only compilation time expressions are allowed in global scope"),
            .non_comptime_default => |e| writer.print("only compilation time expressions are allowed for {s}", .{e.kind}),
            .use_uninit_var => |e| writer.print("variable '{s}' is used uninitialized", .{e.name}),
            .void_array => writer.writeAll("can't declare an array of 'void' values"),
            .void_param => writer.writeAll("function parameters can't be of 'void' type"),
            .void_value => writer.writeAll("value is of type 'void'"),
            .when_arm_duplicate => writer.writeAll("this pattern is already covered by another arm"),
            .when_arm_not_in_union => |e| writer.print("type '{s}' is not part of union '{s}'", .{ e.found, e.expect }),
            .when_non_exhaustive => |e| writer.print("non-exhaustive 'when', missing: '{s}'", .{e.missing}),
            .when_with_non_union => |e| writer.print(
                "using 'when' expression on a non-union type is useless, found: {s}",
                .{e.found},
            ),
        };
    }

    pub fn getHint(self: Self, writer: *Writer) !void {
        try switch (self) {
            .already_declared, .already_declared_field, .already_declared_param => writer.writeAll("this name"),
            .array_mismatch_dim => writer.writeAll("this array access is wrong"),
            .assign_to_constant => writer.writeAll("this variable is declared as a constant"),
            .assign_to_struct_fn => writer.writeAll("this field is a function"),
            .assign_type => writer.writeAll("This is a type, not a value"),
            .big_self_outside_struct => writer.writeAll("used outside a structure"),
            .block_all_path_dont_return => writer.writeAll("this block"),
            .break_val_in_non_val_block => writer.writeAll("can't have this expression"),
            .call_method_on_type, .call_static_on_instance => writer.writeAll("wrong calling convention"),
            .cant_infer_array_type => writer.writeAll("empty arrays don't convey any type information"),
            .cond_alias_non_optional => writer.writeAll("this isn't an optional"),
            .dead_code => writer.writeAll("code after this expression can't be reached"),
            .default_value_type_mismatch => |e| writer.print("this expression is of type '{s}'", .{e.found}),
            .dot_type_on_non_mod => writer.writeAll("this is not a module"),
            .duplicate_field, .duplicate_param => writer.writeAll("this one"),
            .enum_dup_tag => writer.writeAll("this tag"),
            .enum_tag_access => writer.writeAll("this is one of the enum's tag"),
            .enum_unknown_field => writer.writeAll("this name is unknown"),
            .float_equal => writer.writeAll("both sides are 'floats'"),
            .fn_expect_value => writer.writeAll("last expression didn't return a value"),
            .invalid_arithmetic => writer.writeAll("expression is not a numeric type"),
            .invalid_assign_target => writer.writeAll("cannot assign to this expression"),
            .invalid_call_target => writer.writeAll("this is neither a function neither a method"),
            .invalid_comparison => writer.writeAll("expressions have different types"),
            .invalid_logical => |e| writer.print("this expression resolves to a '{s}'", .{e.found}),
            .invalid_unary, .non_bool_cond => writer.writeAll("expression is not a boolean type"),
            .missing_symbol_in_module => writer.writeAll("this symbol is unknown"),
            .missing_else_clause => |e| writer.print("'if' expression is of type '{s}'", .{e.if_type}),
            .missing_field_struct_literal => writer.writeAll("non-exhaustive structure literal"),
            .missing_file_in_module => writer.writeAll("no file matches this name"),
            .missing_function_param, .too_many_fn_args => writer.writeAll("this call"),
            .named_arg_in_bounded => writer.writeAll("this named argument"),
            .no_main => writer.writeAll("in this file"),
            .non_array_indexing => writer.writeAll("this is not an index"),
            .non_comptime_in_global, .non_comptime_default => writer.writeAll("this expression"),
            .non_integer_index => writer.writeAll("this is not an integer"),
            .non_null_comp_optional => writer.writeAll("this is not 'null' literal"),
            .non_struct_field_access => |e| writer.print("expect a structure but found '{s}'", .{e.found}),
            .non_struct_struct_literal => writer.writeAll("this is not a structure"),
            .null_assign_to_non_optional => writer.writeAll("this is not an optinal type"),
            .return_outside_fn, .self_outside_struct => writer.writeAll("here"),
            .too_many_locals, .too_many_types => writer.writeAll("this is the exceding one"),
            .type_mismatch => |e| writer.print("this expression is of type '{s}'", .{e.found}),
            .type_not_in_union => |e| writer.print("this expression is of type '{s}'", .{e.found}),
            .undeclared_field_access, .undeclared_type, .undeclared_var, .use_uninit_var => writer.writeAll("here"),
            .undeclared_block_label => writer.writeAll("this label"),
            .unknow_char_escape => writer.writeAll("unknown character to espace"),
            .unknown_module, .unknown_struct_field => writer.writeAll("this name"),
            .unknown_param, .void_param => writer.writeAll("this parameter"),
            .void_array => writer.writeAll("declared here"),
            .void_value => writer.writeAll("this expression produces no value"),
            .when_arm_not_in_union, .when_arm_duplicate => writer.writeAll("this arm"),
            .when_non_exhaustive => writer.writeAll("this expression"),
            .when_with_non_union => writer.writeAll("this is not an union"),
        };
    }

    pub fn getHelp(self: Self, writer: *Writer) !void {
        try switch (self) {
            .already_declared,
            .already_declared_field,
            .already_declared_param,
            .array_mismatch_dim,
            => writer.writeAll("refer to variable's definition to get array's dimension"),
            .assign_to_struct_fn => writer.writeAll("it is not allowed to modify structures' functions at runtime"),
            .assign_to_constant => writer.writeAll(
                "variables declared with 'const' and function parameters are constant, their value can't be changed",
            ),
            .assign_type => writer.writeAll("types aren't assignable to variables"),
            .big_self_outside_struct => writer.writeAll("'Self' can only be used in structure to refer to the current structure's type"),
            .block_all_path_dont_return => writer.writeAll("when using a block as an expression, all paths must return a value"),
            .break_val_in_non_val_block => writer.writeAll(
                \\you are either trying to return a value from a non expression block (like a 'while' body) or the block
                \\isn't used in an expression
            ),
            .call_method_on_type, .call_static_on_instance => writer.writeAll(
                "static functions can only be called on types and methods can only be called on instances",
            ),
            .cant_infer_array_type => writer.writeAll(
                \\can't extract any type information from an empty array '[]'. you must either declare a type in variable's
                \\signature like: 'var arr: []int = []' or initialize the array with at least one value (not possible every time).
                \\Also, doing 'var arr: []int = []' is equivalent to 'var arr: []int'.
            ),
            .cond_alias_non_optional => writer.writeAll("refer to value's defnintion to see its type or use a regular control flow"),
            .dead_code => writer.writeAll("remove unreachable code"),
            .default_value_type_mismatch => |e| writer.print(
                "modify {s}'s default value to match '{s}' type or change {s}'s type",
                .{ e.kind, e.expect, e.kind },
            ),
            .dot_type_on_non_mod => writer.writeAll("check variable declaration to see it's type"),
            .duplicate_field => writer.writeAll("fields can be defined only once in structure literals"),
            .duplicate_param => writer.writeAll("parameters can be defined only once in function calls"),
            .enum_dup_tag => writer.writeAll("use another name or introduce numbers, underscore, ..."),
            .enum_tag_access => writer.writeAll(
                \\you can either access declarations inside an enum (functions, constants, ...) or test enum's tag
                \\with an 'if' statement like: 'if foo == .a {}' or with pattern matching via 'match'.
            ),
            .enum_unknown_field => writer.writeAll("refer to enum's declaration to see available tags and declarations"),
            .float_equal => writer.writeAll(
                \\floating-point values are approximations to infinitly precise real numbers. 
                \\   If you want to compare floats, you should compare against an Epsilon, like
                \\   value < 1e-6  instead of  value == 0
                \\   value - other < 1e-6  instead of  value < other
            ),
            .fn_expect_value => writer.writeAll("refer to function's declaration to return the correct type with 'return'"),
            .invalid_arithmetic => writer.writeAll("expect a numeric type"),
            .invalid_assign_target => writer.writeAll("can only assign to variables"),
            .invalid_call_target => writer.writeAll("change call target to a function or a method or remove the call"),
            .invalid_comparison => writer.writeAll("expressions must have the same type when compared"),
            .invalid_logical => writer.writeAll("modify the logic to operate on booleans"),
            .invalid_unary => |e| writer.print("can only negate boolean type, found '{s}'", .{e.found}),
            .missing_symbol_in_module => writer.writeAll("refer to module's source code or documentation to ge the list of available symbols"),
            .missing_else_clause => writer.writeAll("add an 'else' block that evaluate to the expected type"),
            .missing_field_struct_literal => writer.writeAll(
                "structure literal expressions must provide an expression for all the fields that don't have a default value",
            ),
            .missing_file_in_module => writer.writeAll("check if the file is in the module or if there is a typo"),
            .missing_function_param => writer.writeAll("all non-default-value parameters must be given a value"),
            .named_arg_in_bounded => writer.writeAll(
                \\when bouding a function/method to a variable, you loose default values informations as the bounded function 
                \\could depend on runtime logic.
            ),
            .no_main => writer.writeAll("add a 'main' function that will be called automatically at execution"),
            .non_array_indexing => writer.writeAll("refer to variable's definition"),
            // TODO: when there will be Range, modify
            .non_integer_index => writer.writeAll("can only use integer values to index arrays"),
            .non_bool_cond => |e| writer.print("'{s}' conditions can only be boolean type", .{e.what}),
            .non_null_comp_optional => writer.writeAll("replace the compared value with 'null' literal or change the condition"),
            .non_struct_field_access => writer.writeAll("refer to variable's definition to know its type"),
            .non_struct_struct_literal => writer.writeAll("refer to type's definition"),
            .null_assign_to_non_optional => writer.writeAll("only optional types declared with '?' can be assigned 'null'"),
            .return_outside_fn => writer.writeAll(
                "return statements are only allow to exit a function's body. In loops, use 'break' otherwise remove the return",
            ),
            .self_outside_struct => writer.writeAll("'self' is a reserved keyword. Use another parameter name"),
            .too_many_locals => writer.writeAll("it's a compiler's limitation for now. Try changing your code"),
            .too_many_fn_args => writer.writeAll("refer to the function's definition to correct the call"),
            .too_many_types => writer.writeAll("it's a compiler limitation but the code shouldn't anyway have that much types. Try rethink you code"),
            .type_mismatch, .type_not_in_union => writer.writeAll("refer to definition to return the correct type"),
            .undeclared_field_access => writer.writeAll("refer to structure's definition to see available fields or modify it"),
            .undeclared_block_label => writer.writeAll("maybe just a typo?"),
            .undeclared_type => writer.writeAll("consider declaring or importing the type before use"),
            .undeclared_var => writer.writeAll("consider declaring or importing the variable before use"),
            .unknow_char_escape => writer.writeAll("valid escape characters are '\\t', '\\n', '\\\\', '\\r'"),
            .unknown_module => writer.writeAll("create the module first and bring it in project scope (or maybe just a typo?)"),
            .unknown_param => writer.writeAll("refer to function's definition to see available parameters"),
            .unknown_struct_field => writer.writeAll("refer to the structure's declaration to see available fields"),
            .non_comptime_default => writer.writeAll("only compilation time known expressions are allowed for default values"),
            .non_comptime_in_global => writer.writeAll("use a constant expression or initialize the value later in a local scope"),
            .use_uninit_var => writer.writeAll("consider initializing the variable before use"),
            .void_array => writer.writeAll("use any other type to declare an array"),
            .void_param => writer.writeAll("use a any other type than 'void' or remove parameter"),
            .void_value => writer.writeAll("consider returning a value from expression"),
            .when_arm_duplicate => writer.writeAll(
                "pattern matching must be exhaustive and each possibility must be matched exactly once",
            ),
            .when_arm_not_in_union => writer.writeAll("remove the arm"),
            .when_non_exhaustive => writer.writeAll(
                "all pattern matching must be exhaustive. You can use '_' as the last prong to catch all the remaining possibilities",
            ),
            .when_with_non_union => writer.writeAll("remove 'when' expression and use the value as it is"),
        };
    }
};
