name: CI
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false  # Allows all jobs to complete even if one fails
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        stage: [parser, analyzer, compiler, vm]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2577+271452d22 
      - run: zig build -Doptimize=ReleaseFast test -Dstage=${{ matrix.stage }}
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
