name: CI
on:
  workflow_dispatch: # Allows manual trigger of the workflow
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false  # Allows all jobs to complete even if one fails
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2577+271452d22
      - name: Debug with SSH
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: build and test
  err-coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        run: python3 tests/errors_coverage.py
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.2577+271452d22 
      - run: zig fmt --check .
